version: '3.4'

services:

  geth:
    image: interlink-geth
    build:
      context: ./geth
    container_name: interlink-geth
    restart: always
    command: nohup geth --testnet --rpc --rpcapi 'admin,miner,eth,net,web3,personal' --rpccorsdomain '*' --rpcaddr 0.0.0.0 --rpcport 8545 --fast
    volumes:
      - ./blockchaindata:/data/blockchain
      - ~/.bash_history:/root/.bash_history
      - ~/.ethereum:/root/.ethereum/
    ports:
      - 8545:8545

networks:
  default:
    external:
      name: interlink
