@startuml
title Storing A Claim With The Reference Automatically Sent To The DID document
autonumber
actor Holder
participant "Service Endpoint" as SE
participant Blockchain order -1
Blockchain <- Holder : setServiceEP
Holder -> Holder : resolveDDO
Holder -> Holder : resolveSEP
Holder -> SE : storeClaim(claim)
SE -> IPFS : storeClaim(claim)
SE <- IPFS : returnHash(hash)
Blockchain <- SE : storeHash(hash)
@enduml